config/routes.rb
Rails.application.routes.draw do

  root to: 'maps#index'
  get 'maps', to: 'maps#index'
  get 'detail', to:'maps#detail'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
    require 'json'
    require 'httpclient'
    require 'uri'
    require 'will_paginate/array'

    api_key = ENV['HOT_API_KEY']
    lat = params["lat"].to_i
    lng = params["lng"].to_i
    distance = params[:distance_id]
    

    data = {
      "key": api_key,
      "range": distance,
      "lat": lat,
      "lng": lng,
      "format": "json"
    }
    

    query = data.to_query
    uri = URI('http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?'+query)

    client = HTTPClient.new
    client.connect_timeout = 100
    client.send_timeout    = 100
    client.receive_timeout = 100
    req = Net::HTTP::Get.new(uri)
    res = client.get(uri)
    res_data = JSON.parse(res.body, symbolize_names: true)

    @cafes = res_data[:results][:shop].paginate(page: params[:page], per_page: 5)
  end
    

  def detail
    @cafe = params.permit(:access, :address, :lat, :lng, :name, :pc, :catch, :open, {:genre => [:catch, :name]}, )
    @genre = params.require(:genre)
    @photo = params.require(:photo)
    gon.lat = @cafe[:lat]
    gon.lng = @cafe[:lng]
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foodlover</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=DotGothic16&display=swap" rel="stylesheet">

    <%= include_gon %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'partial/navbar' %>
    </header>
    <div id="content">
      <div class="content-width">
        <main>
          <%= yield %>
        </main>
      </div>
      <footer>
        <%= render 'partial/footer' %>
      </footer>
    </div>
  </body>
</html>

app/views/maps/detail.html.erb
<div class="col-md-8 col-md-2 mx-auto">
  <div class="card shadow mb-md">
    <div class="card-header">
      <strong><%= @cafe[:name] %></strong>
    </div>
    <div class="card-body">
      <%= image_tag @photo[:pc][:l], class: "card-img-top mb-sm" %>
      <h5 class="card-title font-md"><span class="linear">ジャンル</span></h5>
      <p class="card-text"><%= @genre[:name] %></p>
      <h5 class="card-title font-md"><span class="linear">営業時間</span></h5>
      <p class="card-text"><%= @cafe[:open] %></p>
      <h5 class="card-title font-md"><span class="linear">住所</span></h5>
      <p class="card-text"><%= @cafe[:address] %></p>
      
      <div id="cafemap"></div>

      <h5 class="card-title font-md"><span class="linear">アクセス</span></h5>
      <p class="card-text"><%= @cafe[:access] %></p>
    </div>
  </div>
</div>


<script>
  let cafemap;
  const lat = gon.lat;
  const lng = gon.lng; // コントローラーで定義したインスタンス変数を変数に代入

function initMap(){
  // 現在位置の特定
  LatLng = new google.maps.LatLng(lat, lng);
  cafemap = new google.maps.Map(document.getElementById('cafemap'), {
      center: LatLng,
      zoom: 15
    });
  
  marker = new google.maps.Marker({
    position: LatLng, // マーカーを立てる位置を指定
    map: cafemap, // マーカーを立てる地図を指定
  });

}
</script>

<script
  src="https://maps.googleapis.com/maps/api/js?key=<%="#{ENV['GOOGLE_MAP_API']}"%>&callback=initMap&libraries=&v=weekly"
  async>
</script>

app/views/maps/index.html.erb
<%# Googleマップ %>
<div id="map"></div>

<script>
  let map;
  function initMap() {
    //現在地の取得
    navigator.geolocation.getCurrentPosition(function (pos) {

      let lat = pos.coords.latitude;
      let lng = pos.coords.longitude;

      $.ajax({
        url: '/maps',
        type: 'GET',
        dataType: 'json',
        data: {
          "lat": lat,
          "lng": lng
        },
      });

      LatLng = new google.maps.LatLng(lat, lng);

      // 取得した位置情報を中心に表示
      map = new google.maps.Map(document.getElementById('map'), {
        center: LatLng,
        zoom: 15
      });

      // マーカーの追加
      marker = new google.maps.Marker({
        position: LatLng, // マーカーを立てる位置を指定
        map: map, // マーカーを立てる地図を指定
      });
      myInfoWindow = new google.maps.InfoWindow({
        // 吹き出しに出す文
        content: "イマココ"
      });
      myInfoWindow.open(map, marker);
      google.maps.event.addListener(myInfoWindow, "closeclick", function() {
        google.maps.event.addListenerOnce(marker, "click", function(event) {
        myInfoWindow.open(map, marker);
        });
      });
    });
  }
</script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=<%="#{ENV['GOOGLE_MAP_API']}"%>&callback=initMap&libraries=&v=weekly"
  async>
</script>

<%# 選択ボックス %>
<div class="selection">
  <h4>現在地からの距離</h4>
    <%= form_tag maps_path, method: :get, id:'form' do %>
      <%= select_tag 'distance_id', options_for_select([['選択してください', ''], ['500m以内',2], ['1km以内',3], ['2km以内', 4]]), id: 'distances' %>
      <%= submit_tag "検索", id: "submit" %> 
    <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @cafes, :container => false %>
</div>

<%# 検索結果の表示 %>
<% @cafes.each do |cafe| %>
  <div id="research">
    <div class="row">
      <div class="col-md-7 col-md-2 mx-auto">
        <div class="card shadow mb-md">
          <% if cafe.present? %>
            <%= image_tag cafe[:photo][:pc][:l], class: "card-img-top" %>
            <div class="card-block">
              <div class="card-title mb-md">
                <h4><%= cafe[:name] %></strong></h4>
              </div>
              <div class="card-text left-align pl-sm pr-sm">
                <div class="sub-title mb-sm">
                  <p>＜アクセス＞</p>
                </div>
                <div class="mb-sm">
                  <%= cafe[:access] %>
                </div>
                <div class="center-align">
                  <%= link_to "もっと詳しく", detail_path(cafe), class: "btn letter-spacing mb-md" %>
                </div>
              </div>
            </div> 
          <% end %>    
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @cafes, :container => false %>
</div>

app/views/partial/_footer.html.erb
<div class="font-sm mt-sm">
  (c)2021 FOOD LOVER
</div>
<div class="font-sm">
  Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパー Webサービス</a>
</div>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-light center-align">
  <div class="content-width">
    <%= link_to "FOOD LOVER", root_path, class: "navbarbrand nav-link h2" %>
  </div>
</nav>